using System;
using System.Collections.Generic;
using Mediapipe.Tasks.Components.Containers;
using UnityEngine;

namespace BodylinkSDK
{
    public class MotionGestureDetector : BodylinkBaseGestureDetector
    {
        [Serializable]
        public class MotionFileReference
        {
            [Tooltip("Display name used for this motion in detection results.")]
            public string motionName;
            [Tooltip("Motion JSON generated by the Motion Gesture Editor.")]
            public TextAsset motionFile;
        }

        [Serializable]
        public struct MotionScore
        {
            [Tooltip("Motion name shown in the realtime score list.")]
            public string motionName;
            [Tooltip("Current confidence for this motion.")]
            [Range(0f, 1f)] public float confidence;
        }

        [Serializable]
        private class MotionJsonData
        {
            public string motionName;
            public float duration;
            public float sampleRate;
            public MotionFrameJsonData[] frames;
        }

        [Serializable]
        private class MotionFrameJsonData
        {
            public float time;
            public TrackedPosePoint[] trackedLandmarks;
            public TrackedPoseAngle[] trackedAngles;
            public TrackedPoseWorldPoint[] trackedWorldLandmarks;
        }

        [Serializable]
        private struct TrackedPosePoint
        {
            public int index;
            public float x;
            public float y;
        }

        [Serializable]
        private struct TrackedPoseAngle
        {
            public string name;
            public int a;
            public int b;
            public int c;
            public float angle;
        }

        [Serializable]
        private struct TrackedPoseWorldPoint
        {
            public int index;
            public float x;
            public float y;
            public float z;
        }

        private class MotionTemplate
        {
            public string motionName;
            public float duration;
            public MotionFrameTemplate[] frames;
        }

        private class MotionFrameTemplate
        {
            public float time;
            public float normalizedTime;
            public PosePointSample[] trackedLandmarks;
            public PoseAngleSample[] trackedAngles;
            public PoseWorldPointSample[] trackedWorldLandmarks;
        }

        private readonly struct PosePointSample
        {
            public readonly int Index;
            public readonly Vector2 Position;

            public PosePointSample(int index, Vector2 position)
            {
                Index = index;
                Position = position;
            }
        }

        private readonly struct PoseAngleSample
        {
            public readonly int A;
            public readonly int B;
            public readonly int C;
            public readonly float Angle;

            public PoseAngleSample(int a, int b, int c, float angle)
            {
                A = a;
                B = b;
                C = c;
                Angle = angle;
            }
        }

        private readonly struct PoseWorldPointSample
        {
            public readonly int Index;
            public readonly Vector3 Position;

            public PoseWorldPointSample(int index, Vector3 position)
            {
                Index = index;
                Position = position;
            }
        }

        private sealed class AngleMotionAccumulator
        {
            public readonly int A;
            public readonly int B;
            public readonly int C;
            public bool HasLastAngle;
            public float LastAngle;
            public float MaxDelta;
            public float TotalDelta;

            public AngleMotionAccumulator(int a, int b, int c)
            {
                A = a;
                B = b;
                C = c;
            }
        }

        private struct LivePoseSample
        {
            public float Time;
            public Vector2[] Landmarks;
            public Vector3[] WorldLandmarks;
            public float[] Visibility;
            public bool HasWorldLandmarks;

            public LivePoseSample(float time, Vector2[] landmarks, Vector3[] worldLandmarks, float[] visibility, bool hasWorldLandmarks)
            {
                Time = time;
                Landmarks = landmarks;
                WorldLandmarks = worldLandmarks;
                Visibility = visibility;
                HasWorldLandmarks = hasWorldLandmarks;
            }
        }

        private sealed class PlayerMotionState
        {
            public readonly int PlayerSlot;
            public readonly Dictionary<string, float> CurrentScores = new Dictionary<string, float>();
            public readonly List<MotionScore> MotionScores = new List<MotionScore>();
            public readonly List<LivePoseSample> LiveSamples = new List<LivePoseSample>();
            public float NextSampleTime;
            public string DetectedMotionName = "Analyzing";
            public float DetectedMotionConfidence;
            public string LastNotifiedMotionName = string.Empty;
            public float LastNotifiedMotionConfidence = -1f;
            public string LastLoggedMotionName = string.Empty;
            public float LastLoggedMotionConfidence = -1f;
            public string LastTriggeredMotionName = string.Empty;
            public float LastTriggerTime = float.NegativeInfinity;

            public PlayerMotionState(int playerSlot)
            {
                PlayerSlot = playerSlot;
            }
        }

        private const int MaxSupportedPlayers = 2;
        private const int LandmarkCount = 33;
        private const float MinVectorEpsilon = 0.0001f;
        private const float MinTemplateSpread = 0.0001f;
        private const float LandmarkPerfectDistance = 0.06f;
        private const float LandmarkToleranceDistance = 0.45f;
        private const float WorldPairPerfectDistance = 0.05f;
        private const float WorldPairToleranceDistance = 0.35f;
        private const float MinTrackedVisibility = 0.15f;
        private const float MotionChangeEventConfidenceDelta = 0.01f;
        private const int MinimumCoreAngleSamples = 2;
        private const int MinimumCoreLandmarkSamples = 3;
        private const int MinimumCoreWorldSamples = 3;
        private const float MotionDeltaScaleFactor2D = 0.04f;
        private const float MotionDeltaScaleFactor3D = 0.05f;
        private const float MotionDeltaMin2D = 0.008f;
        private const float MotionDeltaMax2D = 0.08f;
        private const float MotionDeltaMin3D = 0.01f;
        private const float MotionDeltaMax3D = 0.18f;
        private const float MotionDeltaAccumulationMultiplier = 1.8f;
        private const float AngleMotionDeltaThreshold = 7f;
        private const float AngleMotionAccumulationThreshold = 14f;
        private const float MotionDeltaAssistMultiplier = 0.6f;

        public const string MotionsFolderAssetPath = "Assets/MotionGestures";

        [Header("Motion Files")]
        [Tooltip("Drag JSON TextAssets from Assets/MotionGestures here.")]
        [SerializeField] private List<MotionFileReference> motionFiles = new List<MotionFileReference>();

        [Header("Detection Settings")]
        [Tooltip("Selected player shown by the legacy single-player properties and realtime Inspector output. Both supported players are evaluated every frame.")]
        [Range(0, 1)]
        [SerializeField] private int playerSlot;
        [Tooltip("Maximum allowed joint-angle difference before angular matching drops off.")]
        [Range(3f, 90f)]
        [SerializeField] private float angleToleranceDegrees = 35f;
        [Tooltip("Minimum confidence required before a motion is considered detected.")]
        [Range(0f, 1f)]
        [SerializeField] private float detectionThreshold = 0.55f;
        [Tooltip("Also compare against a mirrored version of each motion so left/right-swapped performances can still match.")]
        [SerializeField] private bool includeMirroredComparison = true;
        [Tooltip("Give extra weight to stable core joints such as shoulders, hips, knees, ankles, and feet.")]
        [SerializeField] private bool prioritizeCorePoints = true;
        [Tooltip("Slowest template playback speed to test while matching live motion.")]
        [Range(0.25f, 2f)]
        [SerializeField] private float minTimeScale = 0.75f;
        [Tooltip("Fastest template playback speed to test while matching live motion.")]
        [Range(0.25f, 2f)]
        [SerializeField] private float maxTimeScale = 1.35f;
        [Tooltip("Step size used when sweeping from minimum to maximum template playback speed.")]
        [Range(0.01f, 0.5f)]
        [SerializeField] private float timeScaleStep = 0.1f;
        [Tooltip("How many live pose samples are captured per second for motion matching.")]
        [Range(5f, 60f)]
        [SerializeField] private float samplingRate = 20f;
        [Tooltip("Minimum delay before the same detected motion can trigger again.")]
        [Range(0.05f, 3f)]
        [SerializeField] private float triggerCooldown = 0.6f;
        [Tooltip("Print motion detection changes and confidence values to the Console.")]
        [SerializeField] private bool debugEnabled;

        [Header("Realtime Output")]
        [Tooltip("Best current motion match for the selected player after threshold filtering.")]
        [SerializeField] private string detectedMotionName = "Analyzing";
        [Tooltip("Confidence score for the selected player's best current motion match.")]
        [SerializeField, Range(0f, 1f)] private float detectedMotionConfidence;
        [Tooltip("Selected player's realtime confidence scores for every loaded motion.")]
        [SerializeField] private List<MotionScore> motionScores = new List<MotionScore>();

        private readonly List<MotionTemplate> templates = new List<MotionTemplate>();
        private readonly Dictionary<string, float> currentScores = new Dictionary<string, float>();
        private readonly PlayerMotionState[] playerStates =
        {
            new PlayerMotionState(0),
            new PlayerMotionState(1)
        };

        private readonly Vector2[] currentLandmarks = new Vector2[LandmarkCount];
        private readonly Vector3[] currentWorldLandmarks = new Vector3[LandmarkCount];
        private readonly float[] currentVisibility = new float[LandmarkCount];
        private readonly Vector2[] interpolatedLandmarks = new Vector2[LandmarkCount];
        private readonly Vector3[] interpolatedWorldLandmarks = new Vector3[LandmarkCount];
        private readonly float[] interpolatedVisibility = new float[LandmarkCount];

        private readonly List<float> scoreBuffer = new List<float>(LandmarkCount);
        private readonly List<Vector2> templateSourcePointBuffer = new List<Vector2>(LandmarkCount);
        private readonly List<Vector2> liveSourcePointBuffer = new List<Vector2>(LandmarkCount);
        private readonly List<Vector2> templatePointBuffer = new List<Vector2>(LandmarkCount);
        private readonly List<Vector2> livePointBuffer = new List<Vector2>(LandmarkCount);
        private readonly List<Vector3> templateWorldSourcePointBuffer = new List<Vector3>(LandmarkCount);
        private readonly List<Vector3> liveWorldSourcePointBuffer = new List<Vector3>(LandmarkCount);
        private readonly List<Vector3> templateWorldPointBuffer = new List<Vector3>(LandmarkCount);
        private readonly List<Vector3> liveWorldPointBuffer = new List<Vector3>(LandmarkCount);

        private float maxTemplateDuration = 1f;

        public string DetectedMotionName => GetPlayerState(ResolveSelectedPlayerSlot()).DetectedMotionName;
        public float DetectedMotionConfidence => GetPlayerState(ResolveSelectedPlayerSlot()).DetectedMotionConfidence;
        public IReadOnlyDictionary<string, float> CurrentScores => GetPlayerState(ResolveSelectedPlayerSlot()).CurrentScores;
        public IReadOnlyList<MotionScore> MotionScores => GetPlayerState(ResolveSelectedPlayerSlot()).MotionScores;

        public event Action<string, float> OnMotionChanged;
        public event Action<IReadOnlyList<MotionScore>> OnMotionScoresUpdated;
        public event Action<int, string, float> OnPlayerMotionChanged;
        public event Action<int, IReadOnlyList<MotionScore>> OnPlayerMotionScoresUpdated;

        private void OnEnable()
        {
            RebuildMotionTemplates();
            SyncSelectedPlayerRealtimeOutput();
        }

        private void OnValidate()
        {
            playerSlot = Mathf.Clamp(playerSlot, 0, 1);
            angleToleranceDegrees = Mathf.Clamp(angleToleranceDegrees, 1f, 180f);
            detectionThreshold = Mathf.Clamp01(detectionThreshold);
            minTimeScale = Mathf.Max(0.1f, minTimeScale);
            maxTimeScale = Mathf.Max(minTimeScale, maxTimeScale);
            timeScaleStep = Mathf.Clamp(timeScaleStep, 0.01f, 0.5f);
            samplingRate = Mathf.Clamp(samplingRate, 5f, 120f);
            triggerCooldown = Mathf.Max(0.01f, triggerCooldown);
            RebuildMotionTemplates();
            SyncSelectedPlayerRealtimeOutput();
        }

        private void Update()
        {
            ProcessGesture();
        }

        public override void ProcessGesture()
        {
            if (Bodylink.Instance == null || !Bodylink.Instance.IsInitialized)
            {
                SetNoMatchStateForAllPlayers("Analyzing");
                SyncSelectedPlayerRealtimeOutput();
                return;
            }

            if (templates.Count == 0)
            {
                SetNoMatchStateForAllPlayers("No Motion Files");
                SyncSelectedPlayerRealtimeOutput();
                return;
            }

            float now = Time.time;
            int trackedPlayerCount = Bodylink.Instance.isMultiplayerEnabled ? MaxSupportedPlayers : 1;
            for (int slot = 0; slot < MaxSupportedPlayers; slot++)
            {
                PlayerMotionState playerState = GetPlayerState(slot);
                if (slot >= trackedPlayerCount)
                {
                    SetNoMatchState(playerState, "Analyzing");
                    continue;
                }

                if (!TryReadPlayerLandmarks(slot, currentLandmarks, currentWorldLandmarks, currentVisibility, out bool hasWorldLandmarks))
                {
                    SetNoMatchState(playerState, "Analyzing");
                    continue;
                }

                if (now >= playerState.NextSampleTime)
                {
                    PushLiveSample(playerState, now, currentLandmarks, currentWorldLandmarks, currentVisibility, hasWorldLandmarks);
                    playerState.NextSampleTime = now + (1f / Mathf.Max(1f, samplingRate));
                }

                if (playerState.LiveSamples.Count < 3)
                {
                    SetNoMatchState(playerState, "Analyzing");
                    continue;
                }

                EvaluateMotionTemplates(playerState, now);
            }

            SyncSelectedPlayerRealtimeOutput();
        }

        public float GetMotionConfidence(string motionName)
        {
            return GetMotionConfidence(ResolveSelectedPlayerSlot(), motionName);
        }

        public float GetMotionConfidence(int targetPlayerSlot, string motionName)
        {
            if (string.IsNullOrEmpty(motionName))
            {
                return 0f;
            }

            PlayerMotionState playerState = GetPlayerState(targetPlayerSlot);
            return playerState.CurrentScores.TryGetValue(motionName, out float score) ? score : 0f;
        }

        public string GetBestMotion(float threshold = -1f)
        {
            return GetBestMotion(ResolveSelectedPlayerSlot(), threshold);
        }

        public string GetBestMotion(int targetPlayerSlot, float threshold = -1f)
        {
            float requiredThreshold = threshold >= 0f ? threshold : detectionThreshold;
            PlayerMotionState playerState = GetPlayerState(targetPlayerSlot);
            if (playerState.DetectedMotionConfidence < requiredThreshold)
            {
                return "Analyzing";
            }

            return playerState.DetectedMotionName;
        }

        public string GetDetectedMotionName(int targetPlayerSlot)
        {
            return GetPlayerState(targetPlayerSlot).DetectedMotionName;
        }

        public float GetDetectedMotionConfidence(int targetPlayerSlot)
        {
            return GetPlayerState(targetPlayerSlot).DetectedMotionConfidence;
        }

        public IReadOnlyList<MotionScore> GetMotionScores(int targetPlayerSlot)
        {
            return GetPlayerState(targetPlayerSlot).MotionScores;
        }

        public IReadOnlyDictionary<string, float> GetCurrentScores(int targetPlayerSlot)
        {
            return GetPlayerState(targetPlayerSlot).CurrentScores;
        }

        private int ResolveSelectedPlayerSlot()
        {
            if (Bodylink.Instance == null || !Bodylink.Instance.isMultiplayerEnabled)
            {
                return 0;
            }

            if (Bodylink.Instance.bodylinkAvatar == null ||
                Bodylink.Instance.bodylinkAvatar.players == null ||
                Bodylink.Instance.bodylinkAvatar.players.Length == 0)
            {
                return 0;
            }

            return Mathf.Clamp(playerSlot, 0, Mathf.Min(Bodylink.Instance.bodylinkAvatar.players.Length - 1, MaxSupportedPlayers - 1));
        }

        private PlayerMotionState GetPlayerState(int targetPlayerSlot)
        {
            int slot = Mathf.Clamp(targetPlayerSlot, 0, MaxSupportedPlayers - 1);
            return playerStates[slot];
        }

        private bool TryReadPlayerLandmarks(int slot, Vector2[] landmarksOut, Vector3[] worldLandmarksOut, float[] visibilityOut, out bool hasWorldLandmarks)
        {
            hasWorldLandmarks = false;
            if (players == null || landmarksOut == null || visibilityOut == null || worldLandmarksOut == null)
            {
                return false;
            }

            if (slot < 0 || slot >= players.Length || players[slot] == null)
            {
                return false;
            }

            List<NormalizedLandmark> landmarks = players[slot].bodyRawPoints2D;
            if (landmarks == null || landmarks.Count < LandmarkCount)
            {
                return false;
            }

            List<Landmark> worldLandmarks = players[slot].bodyRawPoints3D;
            hasWorldLandmarks = worldLandmarks != null && worldLandmarks.Count >= LandmarkCount;

            for (int i = 0; i < LandmarkCount; i++)
            {
                landmarksOut[i] = new Vector2(landmarks[i].x, landmarks[i].y);

                if (hasWorldLandmarks)
                {
                    worldLandmarksOut[i] = new Vector3(worldLandmarks[i].x, worldLandmarks[i].y, worldLandmarks[i].z);
                }
                else
                {
                    worldLandmarksOut[i] = Vector3.zero;
                }

                float visibility = landmarks[i].visibility.GetValueOrDefault(1f);
                float presence = landmarks[i].presence.GetValueOrDefault(1f);
                visibilityOut[i] = Mathf.Max(visibility, presence);
            }

            return true;
        }

        private void PushLiveSample(PlayerMotionState playerState, float sampleTime, Vector2[] landmarks, Vector3[] worldLandmarks, float[] visibility, bool hasWorldLandmarks)
        {
            if (playerState == null)
            {
                return;
            }

            Vector2[] landmarksCopy = new Vector2[LandmarkCount];
            Vector3[] worldLandmarksCopy = new Vector3[LandmarkCount];
            float[] visibilityCopy = new float[LandmarkCount];
            Array.Copy(landmarks, landmarksCopy, LandmarkCount);
            Array.Copy(worldLandmarks, worldLandmarksCopy, LandmarkCount);
            Array.Copy(visibility, visibilityCopy, LandmarkCount);

            playerState.LiveSamples.Add(new LivePoseSample(sampleTime, landmarksCopy, worldLandmarksCopy, visibilityCopy, hasWorldLandmarks));
            PruneLiveSamples(playerState.LiveSamples, sampleTime);
        }

        private void PruneLiveSamples(List<LivePoseSample> samples, float now)
        {
            if (samples == null)
            {
                return;
            }

            float keepDuration = Mathf.Max((maxTemplateDuration * Mathf.Max(maxTimeScale, 1f)) + 0.8f, 1.5f);
            float minTime = now - keepDuration;

            int removeCount = 0;
            while (removeCount < samples.Count && samples[removeCount].Time < minTime)
            {
                removeCount++;
            }

            if (removeCount > 0)
            {
                samples.RemoveRange(0, removeCount);
            }
        }

        private void EvaluateMotionTemplates(PlayerMotionState playerState, float now)
        {
            if (playerState == null)
            {
                return;
            }

            playerState.CurrentScores.Clear();
            playerState.MotionScores.Clear();

            Dictionary<string, float> bestScoresByMotionName = new Dictionary<string, float>(StringComparer.Ordinal);
            List<string> motionNamesInDisplayOrder = new List<string>(templates.Count);

            string bestMotion = "Analyzing";
            float bestConfidence = 0f;

            for (int i = 0; i < templates.Count; i++)
            {
                MotionTemplate template = templates[i];
                float confidence = CalculateMotionConfidence(template, playerState.LiveSamples);

                string motionName = ResolveTemplateDisplayName(template.motionName);

                if (bestScoresByMotionName.TryGetValue(motionName, out float existing))
                {
                    if (confidence > existing)
                    {
                        bestScoresByMotionName[motionName] = confidence;
                    }
                }
                else
                {
                    bestScoresByMotionName[motionName] = confidence;
                    motionNamesInDisplayOrder.Add(motionName);
                }
            }

            for (int i = 0; i < motionNamesInDisplayOrder.Count; i++)
            {
                string motionName = motionNamesInDisplayOrder[i];
                float confidence = bestScoresByMotionName[motionName];
                playerState.CurrentScores[motionName] = confidence;
                playerState.MotionScores.Add(new MotionScore
                {
                    motionName = motionName,
                    confidence = confidence
                });

                if (confidence > bestConfidence)
                {
                    bestConfidence = confidence;
                    bestMotion = motionName;
                }
            }

            playerState.DetectedMotionConfidence = Mathf.Clamp01(bestConfidence);
            playerState.DetectedMotionName = playerState.DetectedMotionConfidence >= detectionThreshold ? bestMotion : "Analyzing";
            NotifyPlayerMotionScoresUpdated(playerState);
            NotifyPlayerMotionChangedIfNeeded(playerState);

            TryTriggerDetectedMotion(playerState, now);

            if (debugEnabled &&
                (playerState.DetectedMotionName != playerState.LastLoggedMotionName ||
                 Mathf.Abs(playerState.DetectedMotionConfidence - playerState.LastLoggedMotionConfidence) > 0.01f))
            {
                Debug.Log("[MotionGestureDetector] Player " + (playerState.PlayerSlot + 1) + " Motion: " +
                          playerState.DetectedMotionName + " (" + playerState.DetectedMotionConfidence.ToString("0.000") + ")");
                playerState.LastLoggedMotionName = playerState.DetectedMotionName;
                playerState.LastLoggedMotionConfidence = playerState.DetectedMotionConfidence;
            }
        }

        private void TryTriggerDetectedMotion(PlayerMotionState playerState, float now)
        {
            if (playerState == null ||
                playerState.DetectedMotionName == "Analyzing" ||
                playerState.DetectedMotionConfidence < detectionThreshold)
            {
                return;
            }

            bool isDifferentMotion = !string.Equals(playerState.LastTriggeredMotionName, playerState.DetectedMotionName, StringComparison.Ordinal);
            bool cooldownElapsed = (now - playerState.LastTriggerTime) >= triggerCooldown;
            if (!isDifferentMotion && !cooldownElapsed)
            {
                return;
            }

            OnGestureDetect(playerState.PlayerSlot, playerState.DetectedMotionName, playerState.DetectedMotionConfidence);
            playerState.LastTriggeredMotionName = playerState.DetectedMotionName;
            playerState.LastTriggerTime = now;
        }

        private float CalculateMotionConfidence(MotionTemplate template, List<LivePoseSample> samples)
        {
            if (template == null || template.frames == null || template.frames.Length < 2 || samples == null || samples.Count < 2)
            {
                return 0f;
            }

            float bestConfidence = 0f;
            float latestTime = samples[samples.Count - 1].Time;

            for (float scale = minTimeScale; scale <= maxTimeScale + 0.0001f; scale += timeScaleStep)
            {
                float windowDuration = Mathf.Max(template.duration * scale, 0.15f);
                float startTime = latestTime - windowDuration;
                if (samples[0].Time > startTime)
                {
                    continue;
                }

                if (!TryCalculateSequenceConfidence(template, samples, startTime, windowDuration, mirror: false, out float sequenceConfidence))
                {
                    continue;
                }

                if (includeMirroredComparison && TryCalculateSequenceConfidence(template, samples, startTime, windowDuration, mirror: true, out float mirroredConfidence))
                {
                    sequenceConfidence = Mathf.Max(sequenceConfidence, mirroredConfidence);
                }

                if (sequenceConfidence > bestConfidence)
                {
                    bestConfidence = sequenceConfidence;
                }
            }

            return bestConfidence;
        }

        private bool TryCalculateSequenceConfidence(MotionTemplate template, List<LivePoseSample> samples, float startTime, float windowDuration, bool mirror, out float confidence)
        {
            confidence = 0f;
            if (template == null || template.frames == null || template.frames.Length == 0 || samples == null || samples.Count == 0)
            {
                return false;
            }

            scoreBuffer.Clear();
            int validFrameCount = 0;
            int lowScoreCount = 0;

            for (int i = 0; i < template.frames.Length; i++)
            {
                MotionFrameTemplate frame = template.frames[i];
                float targetTime = startTime + (frame.normalizedTime * windowDuration);
                if (!TryInterpolateLivePose(samples, targetTime, interpolatedLandmarks, interpolatedWorldLandmarks, interpolatedVisibility, out bool hasLiveWorldLandmarks))
                {
                    continue;
                }

                if (!TryCalculateFrameConfidence(frame, interpolatedLandmarks, interpolatedWorldLandmarks, interpolatedVisibility, mirror, hasLiveWorldLandmarks, out float frameConfidence))
                {
                    continue;
                }

                scoreBuffer.Add(frameConfidence);
                validFrameCount++;
                if (frameConfidence < 0.35f)
                {
                    lowScoreCount++;
                }
            }

            int minimumRequiredFrames = Mathf.Max(2, Mathf.CeilToInt(template.frames.Length * 0.5f));
            if (validFrameCount < minimumRequiredFrames)
            {
                return false;
            }

            scoreBuffer.Sort();
            int dropCount = 0;
            if (scoreBuffer.Count >= 8)
            {
                dropCount = 2;
            }
            else if (scoreBuffer.Count >= 5)
            {
                dropCount = 1;
            }

            float baseConfidence = ComputeWeightedBaseScore(scoreBuffer, dropCount);
            float lowScoreRatio = lowScoreCount / (float)Mathf.Max(validFrameCount, 1);
            float mismatchPenalty = ComputeMismatchPenalty(lowScoreRatio, validFrameCount);
            float coverage = validFrameCount / (float)template.frames.Length;
            confidence = Mathf.Clamp01(baseConfidence * mismatchPenalty * coverage);
            return true;
        }

        private bool TryCalculateFrameConfidence(
            MotionFrameTemplate frame,
            Vector2[] liveLandmarks,
            Vector3[] liveWorldLandmarks,
            float[] liveVisibility,
            bool mirror,
            bool hasLiveWorldLandmarks,
            out float confidence)
        {
            confidence = 0f;
            bool hasAngleConfidence = TryCalculateAngleFrameConfidence(frame, liveLandmarks, liveVisibility, mirror, out float angleConfidence);
            bool hasLandmarkConfidence = TryCalculateLandmarkFrameConfidence(frame, liveLandmarks, liveVisibility, mirror, out float landmarkConfidence);
            bool hasWorldConfidence = TryCalculateWorldLandmarkFrameConfidence(frame, liveWorldLandmarks, liveVisibility, mirror, hasLiveWorldLandmarks, out float worldConfidence);

            if (!hasAngleConfidence && !hasLandmarkConfidence && !hasWorldConfidence)
            {
                return false;
            }

            if (hasWorldConfidence)
            {
                float angleWeight = hasAngleConfidence ? (frame.trackedAngles != null && frame.trackedAngles.Length >= 4 ? 0.25f : 0.15f) : 0f;
                float landmarkWeight = hasLandmarkConfidence ? 0.20f : 0f;
                float worldWeight = 1f - angleWeight - landmarkWeight;
                float blendedConfidence = (worldConfidence * worldWeight) +
                    (hasAngleConfidence ? angleConfidence * angleWeight : 0f) +
                    (hasLandmarkConfidence ? landmarkConfidence * landmarkWeight : 0f);
                confidence = Mathf.Max(worldConfidence, blendedConfidence);
                return true;
            }

            if (hasAngleConfidence && hasLandmarkConfidence)
            {
                float angleWeight = frame.trackedAngles != null && frame.trackedAngles.Length >= 4 ? 0.60f : 0.45f;
                float blendedConfidence = (angleConfidence * angleWeight) + (landmarkConfidence * (1f - angleWeight));
                confidence = Mathf.Max(angleConfidence, blendedConfidence);
                return true;
            }

            confidence = hasLandmarkConfidence ? landmarkConfidence : angleConfidence;
            return true;
        }

        private bool TryCalculateAngleFrameConfidence(MotionFrameTemplate frame, Vector2[] liveLandmarks, float[] liveVisibility, bool mirror, out float confidence)
        {
            if (prioritizeCorePoints &&
                TryCalculateAngleFrameConfidenceInternal(frame, liveLandmarks, liveVisibility, mirror, coreOnly: true, MinimumCoreAngleSamples, out confidence))
            {
                return true;
            }

            return TryCalculateAngleFrameConfidenceInternal(frame, liveLandmarks, liveVisibility, mirror, coreOnly: false, 1, out confidence);
        }

        private bool TryCalculateLandmarkFrameConfidence(MotionFrameTemplate frame, Vector2[] liveLandmarks, float[] liveVisibility, bool mirror, out float confidence)
        {
            confidence = 0f;

            if (frame == null ||
                frame.trackedLandmarks == null ||
                frame.trackedLandmarks.Length < 2 ||
                liveLandmarks == null ||
                liveLandmarks.Length < LandmarkCount)
            {
                return false;
            }

            bool collectedCorePoints = prioritizeCorePoints &&
                TryCollectLandmarkSources(frame, liveLandmarks, liveVisibility, mirror, coreOnly: true, MinimumCoreLandmarkSamples);
            if (!collectedCorePoints &&
                !TryCollectLandmarkSources(frame, liveLandmarks, liveVisibility, mirror, coreOnly: false, 2))
            {
                return false;
            }

            bool hasValidTransform = false;
            float bestConfidence = 0f;

            for (int transform = 0; transform < 4; transform++)
            {
                bool flipX = (transform & 1) != 0;
                bool flipY = (transform & 2) != 0;

                if (!TryCalculateLandmarkFrameConfidenceForTransform(flipX, flipY, out float candidateConfidence))
                {
                    continue;
                }

                hasValidTransform = true;
                if (candidateConfidence > bestConfidence)
                {
                    bestConfidence = candidateConfidence;
                }
            }

            if (!hasValidTransform)
            {
                return false;
            }

            confidence = bestConfidence;
            return true;
        }

        private bool TryCalculateLandmarkFrameConfidenceForTransform(bool flipX, bool flipY, out float confidence)
        {
            confidence = 0f;
            templatePointBuffer.Clear();
            livePointBuffer.Clear();

            for (int i = 0; i < templateSourcePointBuffer.Count; i++)
            {
                Vector2 templatePoint = templateSourcePointBuffer[i];
                Vector2 livePoint = liveSourcePointBuffer[i];

                if (flipX)
                {
                    livePoint.x = 1f - livePoint.x;
                }

                if (flipY)
                {
                    livePoint.y = 1f - livePoint.y;
                }

                templatePointBuffer.Add(templatePoint);
                livePointBuffer.Add(livePoint);
            }

            if (!TryNormalizePointSet(templatePointBuffer) || !TryNormalizePointSet(livePointBuffer))
            {
                return false;
            }

            float dot = 0f;
            float cross = 0f;
            for (int i = 0; i < templatePointBuffer.Count; i++)
            {
                Vector2 templatePoint = templatePointBuffer[i];
                Vector2 livePoint = livePointBuffer[i];
                dot += (livePoint.x * templatePoint.x) + (livePoint.y * templatePoint.y);
                cross += (livePoint.x * templatePoint.y) - (livePoint.y * templatePoint.x);
            }

            float rotation = Mathf.Atan2(cross, dot);
            float cos = Mathf.Cos(rotation);
            float sin = Mathf.Sin(rotation);

            float totalScore = 0f;
            int lowScoreCount = 0;

            for (int i = 0; i < templatePointBuffer.Count; i++)
            {
                Vector2 templatePoint = templatePointBuffer[i];
                Vector2 livePoint = livePointBuffer[i];
                Vector2 rotatedLivePoint = new Vector2(
                    (livePoint.x * cos) - (livePoint.y * sin),
                    (livePoint.x * sin) + (livePoint.y * cos));

                float distance = Vector2.Distance(rotatedLivePoint, templatePoint);
                float score = ScoreDistanceDelta(distance, LandmarkPerfectDistance, LandmarkToleranceDistance);
                totalScore += score;
                if (score < 0.35f)
                {
                    lowScoreCount++;
                }
            }

            float baseConfidence = totalScore / templatePointBuffer.Count;
            float lowScoreRatio = lowScoreCount / (float)templatePointBuffer.Count;
            float mismatchPenalty = ComputeMismatchPenalty(lowScoreRatio, templatePointBuffer.Count);
            confidence = Mathf.Clamp01(baseConfidence * mismatchPenalty);
            return true;
        }

        private bool TryCalculateWorldLandmarkFrameConfidence(
            MotionFrameTemplate frame,
            Vector3[] liveWorldLandmarks,
            float[] liveVisibility,
            bool mirror,
            bool hasLiveWorldLandmarks,
            out float confidence)
        {
            confidence = 0f;

            if (!hasLiveWorldLandmarks ||
                frame == null ||
                frame.trackedWorldLandmarks == null ||
                frame.trackedWorldLandmarks.Length < 3 ||
                liveWorldLandmarks == null ||
                liveWorldLandmarks.Length < LandmarkCount ||
                liveVisibility == null ||
                liveVisibility.Length < LandmarkCount)
            {
                return false;
            }

            bool collectedCorePoints = prioritizeCorePoints &&
                TryCollectWorldLandmarkSources(frame, liveWorldLandmarks, liveVisibility, mirror, coreOnly: true, MinimumCoreWorldSamples);
            if (!collectedCorePoints &&
                !TryCollectWorldLandmarkSources(frame, liveWorldLandmarks, liveVisibility, mirror, coreOnly: false, 3))
            {
                return false;
            }

            templateWorldPointBuffer.Clear();
            liveWorldPointBuffer.Clear();
            templateWorldPointBuffer.AddRange(templateWorldSourcePointBuffer);
            liveWorldPointBuffer.AddRange(liveWorldSourcePointBuffer);

            if (!TryNormalizePointSet3D(templateWorldPointBuffer) || !TryNormalizePointSet3D(liveWorldPointBuffer))
            {
                return false;
            }

            float totalScore = 0f;
            int pairCount = 0;
            int lowScoreCount = 0;

            for (int i = 0; i < templateWorldPointBuffer.Count - 1; i++)
            {
                for (int j = i + 1; j < templateWorldPointBuffer.Count; j++)
                {
                    float templateDistance = Vector3.Distance(templateWorldPointBuffer[i], templateWorldPointBuffer[j]);
                    float liveDistance = Vector3.Distance(liveWorldPointBuffer[i], liveWorldPointBuffer[j]);
                    float delta = Mathf.Abs(templateDistance - liveDistance);
                    float score = ScoreDistanceDelta(delta, WorldPairPerfectDistance, WorldPairToleranceDistance);
                    totalScore += score;
                    pairCount++;
                    if (score < 0.35f)
                    {
                        lowScoreCount++;
                    }
                }
            }

            if (pairCount <= 0)
            {
                return false;
            }

            float baseConfidence = totalScore / pairCount;
            float lowScoreRatio = lowScoreCount / (float)pairCount;
            float mismatchPenalty = ComputeMismatchPenalty(lowScoreRatio, pairCount);
            confidence = Mathf.Clamp01(baseConfidence * mismatchPenalty);
            return true;
        }

        private bool TryInterpolateLivePose(List<LivePoseSample> samples, float targetTime, Vector2[] landmarksOut, Vector3[] worldLandmarksOut, float[] visibilityOut, out bool hasWorldLandmarks)
        {
            hasWorldLandmarks = false;
            if (samples == null || samples.Count == 0 || landmarksOut == null || worldLandmarksOut == null || visibilityOut == null)
            {
                return false;
            }

            if (targetTime <= samples[0].Time)
            {
                Array.Copy(samples[0].Landmarks, landmarksOut, LandmarkCount);
                Array.Copy(samples[0].WorldLandmarks, worldLandmarksOut, LandmarkCount);
                Array.Copy(samples[0].Visibility, visibilityOut, LandmarkCount);
                hasWorldLandmarks = samples[0].HasWorldLandmarks;
                return true;
            }

            for (int i = 1; i < samples.Count; i++)
            {
                LivePoseSample right = samples[i];
                if (targetTime > right.Time)
                {
                    continue;
                }

                LivePoseSample left = samples[i - 1];
                float span = Mathf.Max(right.Time - left.Time, 0.0001f);
                float t = Mathf.Clamp01((targetTime - left.Time) / span);

                for (int j = 0; j < LandmarkCount; j++)
                {
                    landmarksOut[j] = Vector2.Lerp(left.Landmarks[j], right.Landmarks[j], t);
                    worldLandmarksOut[j] = Vector3.Lerp(left.WorldLandmarks[j], right.WorldLandmarks[j], t);
                    visibilityOut[j] = Mathf.Lerp(left.Visibility[j], right.Visibility[j], t);
                }

                hasWorldLandmarks = left.HasWorldLandmarks && right.HasWorldLandmarks;
                return true;
            }

            LivePoseSample last = samples[samples.Count - 1];
            if (targetTime > last.Time + 0.02f)
            {
                return false;
            }

            Array.Copy(last.Landmarks, landmarksOut, LandmarkCount);
            Array.Copy(last.WorldLandmarks, worldLandmarksOut, LandmarkCount);
            Array.Copy(last.Visibility, visibilityOut, LandmarkCount);
            hasWorldLandmarks = last.HasWorldLandmarks;
            return true;
        }

        private static bool TryNormalizePointSet(List<Vector2> points)
        {
            if (points == null || points.Count < 2)
            {
                return false;
            }

            Vector2 centroid = Vector2.zero;
            for (int i = 0; i < points.Count; i++)
            {
                centroid += points[i];
            }
            centroid /= points.Count;

            float sqrMagnitudeSum = 0f;
            for (int i = 0; i < points.Count; i++)
            {
                Vector2 centered = points[i] - centroid;
                points[i] = centered;
                sqrMagnitudeSum += centered.sqrMagnitude;
            }

            float scale = Mathf.Sqrt(sqrMagnitudeSum / points.Count);
            if (scale < MinTemplateSpread)
            {
                return false;
            }

            for (int i = 0; i < points.Count; i++)
            {
                points[i] /= scale;
            }

            return true;
        }

        private static bool TryNormalizePointSet3D(List<Vector3> points)
        {
            if (points == null || points.Count < 2)
            {
                return false;
            }

            Vector3 centroid = Vector3.zero;
            for (int i = 0; i < points.Count; i++)
            {
                centroid += points[i];
            }
            centroid /= points.Count;

            float sqrMagnitudeSum = 0f;
            for (int i = 0; i < points.Count; i++)
            {
                Vector3 centered = points[i] - centroid;
                points[i] = centered;
                sqrMagnitudeSum += centered.sqrMagnitude;
            }

            float scale = Mathf.Sqrt(sqrMagnitudeSum / points.Count);
            if (scale < MinTemplateSpread)
            {
                return false;
            }

            for (int i = 0; i < points.Count; i++)
            {
                points[i] /= scale;
            }

            return true;
        }

        private static float ComputeWeightedBaseScore(List<float> sortedScores, int startIndex)
        {
            if (sortedScores == null)
            {
                return 0f;
            }

            int count = sortedScores.Count - startIndex;
            if (count <= 0)
            {
                return 0f;
            }

            if (count == 1)
            {
                return sortedScores[sortedScores.Count - 1];
            }

            if (count == 2)
            {
                float low = sortedScores[startIndex];
                float high = sortedScores[startIndex + 1];
                return (high * 0.75f) + (low * 0.25f);
            }

            if (count == 3)
            {
                float low = sortedScores[startIndex];
                float mid = sortedScores[startIndex + 1];
                float high = sortedScores[startIndex + 2];
                return (high * 0.50f) + (mid * 0.30f) + (low * 0.20f);
            }

            float total = 0f;
            for (int i = startIndex; i < sortedScores.Count; i++)
            {
                total += sortedScores[i];
            }

            return total / count;
        }

        private static float ComputeMismatchPenalty(float lowScoreRatio, int sampleCount)
        {
            lowScoreRatio = Mathf.Clamp01(lowScoreRatio);
            int clampedSampleCount = Mathf.Max(sampleCount, 1);
            float validRatio = 1f - lowScoreRatio;

            if (clampedSampleCount <= 2)
            {
                return Mathf.Lerp(1f, validRatio, 0.25f);
            }

            if (clampedSampleCount <= 4)
            {
                return Mathf.Pow(validRatio, 0.65f);
            }

            if (clampedSampleCount <= 7)
            {
                return Mathf.Pow(validRatio, 1.00f);
            }

            return Mathf.Pow(validRatio, 1.6f);
        }

        private static float ScoreAngleDelta(float delta, float perfectWindow, float tolerance)
        {
            if (delta <= perfectWindow)
            {
                return 1f;
            }

            if (delta >= tolerance)
            {
                return 0f;
            }

            float normalized = Mathf.InverseLerp(perfectWindow, tolerance, delta);
            return 1f - (normalized * normalized);
        }

        private static float ScoreDistanceDelta(float distance, float perfectDistance, float tolerance)
        {
            if (distance <= perfectDistance)
            {
                return 1f;
            }

            if (distance >= tolerance)
            {
                return 0f;
            }

            float normalized = Mathf.InverseLerp(perfectDistance, tolerance, distance);
            return 1f - (normalized * normalized);
        }

        private static bool TryCalculateJointAngle(Vector2[] landmarks, int a, int b, int c, out float angle)
        {
            angle = 0f;
            if (landmarks == null ||
                a < 0 || a >= landmarks.Length ||
                b < 0 || b >= landmarks.Length ||
                c < 0 || c >= landmarks.Length)
            {
                return false;
            }

            Vector2 fromPivotToA = landmarks[a] - landmarks[b];
            Vector2 fromPivotToC = landmarks[c] - landmarks[b];

            float magnitudeA = fromPivotToA.magnitude;
            float magnitudeC = fromPivotToC.magnitude;
            if (magnitudeA < MinVectorEpsilon || magnitudeC < MinVectorEpsilon)
            {
                return false;
            }

            float dot = Vector2.Dot(fromPivotToA / magnitudeA, fromPivotToC / magnitudeC);
            dot = Mathf.Clamp(dot, -1f, 1f);
            angle = Mathf.Acos(dot) * Mathf.Rad2Deg;
            return true;
        }

        private static int MirrorLandmarkIndex(int index)
        {
            switch (index)
            {
                case 1: return 4;
                case 2: return 5;
                case 3: return 6;
                case 4: return 1;
                case 5: return 2;
                case 6: return 3;
                case 7: return 8;
                case 8: return 7;
                case 9: return 10;
                case 10: return 9;
                case 11: return 12;
                case 12: return 11;
                case 13: return 14;
                case 14: return 13;
                case 15: return 16;
                case 16: return 15;
                case 17: return 18;
                case 18: return 17;
                case 19: return 20;
                case 20: return 19;
                case 21: return 22;
                case 22: return 21;
                case 23: return 24;
                case 24: return 23;
                case 25: return 26;
                case 26: return 25;
                case 27: return 28;
                case 28: return 27;
                case 29: return 30;
                case 30: return 29;
                case 31: return 32;
                case 32: return 31;
                default: return index;
            }
        }

        private static bool HasSufficientVisibility(float[] visibility, int index)
        {
            if (visibility == null || index < 0 || index >= visibility.Length)
            {
                return false;
            }

            return visibility[index] >= MinTrackedVisibility;
        }

        private bool TryCalculateAngleFrameConfidenceInternal(
            MotionFrameTemplate frame,
            Vector2[] liveLandmarks,
            float[] liveVisibility,
            bool mirror,
            bool coreOnly,
            int minimumRequiredSamples,
            out float confidence)
        {
            confidence = 0f;
            if (frame == null || frame.trackedAngles == null || frame.trackedAngles.Length == 0)
            {
                return false;
            }

            float perfectWindow = Mathf.Min(15f, angleToleranceDegrees * 0.5f);
            float effectiveTolerance = Mathf.Max(angleToleranceDegrees, perfectWindow + 0.001f);

            scoreBuffer.Clear();
            int lowScoreCount = 0;

            for (int i = 0; i < frame.trackedAngles.Length; i++)
            {
                PoseAngleSample sample = frame.trackedAngles[i];
                if (coreOnly && !IsCoreAngleSample(sample))
                {
                    continue;
                }

                int a = mirror ? MirrorLandmarkIndex(sample.A) : sample.A;
                int b = mirror ? MirrorLandmarkIndex(sample.B) : sample.B;
                int c = mirror ? MirrorLandmarkIndex(sample.C) : sample.C;

                if (!HasSufficientVisibility(liveVisibility, a) ||
                    !HasSufficientVisibility(liveVisibility, b) ||
                    !HasSufficientVisibility(liveVisibility, c))
                {
                    continue;
                }

                if (!TryCalculateJointAngle(liveLandmarks, a, b, c, out float liveAngle))
                {
                    continue;
                }

                float delta = Mathf.Abs(Mathf.DeltaAngle(liveAngle, sample.Angle));
                float score = ScoreAngleDelta(delta, perfectWindow, effectiveTolerance);
                scoreBuffer.Add(score);
                if (score < 0.35f)
                {
                    lowScoreCount++;
                }
            }

            if (scoreBuffer.Count < minimumRequiredSamples)
            {
                return false;
            }

            scoreBuffer.Sort();
            int dropCount = 0;
            if (scoreBuffer.Count >= 8)
            {
                dropCount = 2;
            }
            else if (scoreBuffer.Count >= 5)
            {
                dropCount = 1;
            }

            float baseConfidence = ComputeWeightedBaseScore(scoreBuffer, dropCount);
            float lowScoreRatio = lowScoreCount / (float)Mathf.Max(scoreBuffer.Count, 1);
            float mismatchPenalty = ComputeMismatchPenalty(lowScoreRatio, scoreBuffer.Count);
            confidence = Mathf.Clamp01(baseConfidence * mismatchPenalty);
            return true;
        }

        private bool TryCollectLandmarkSources(
            MotionFrameTemplate frame,
            Vector2[] liveLandmarks,
            float[] liveVisibility,
            bool mirror,
            bool coreOnly,
            int minimumRequiredSamples)
        {
            templateSourcePointBuffer.Clear();
            liveSourcePointBuffer.Clear();

            for (int i = 0; i < frame.trackedLandmarks.Length; i++)
            {
                PosePointSample point = frame.trackedLandmarks[i];
                if (coreOnly && !IsCoreLandmarkIndex(point.Index))
                {
                    continue;
                }

                int liveIndex = mirror ? MirrorLandmarkIndex(point.Index) : point.Index;
                if (!IsValidLandmarkIndex(liveIndex))
                {
                    continue;
                }

                if (!HasSufficientVisibility(liveVisibility, liveIndex))
                {
                    continue;
                }

                templateSourcePointBuffer.Add(point.Position);
                liveSourcePointBuffer.Add(liveLandmarks[liveIndex]);
            }

            return templateSourcePointBuffer.Count >= minimumRequiredSamples &&
                liveSourcePointBuffer.Count >= minimumRequiredSamples;
        }

        private bool TryCollectWorldLandmarkSources(
            MotionFrameTemplate frame,
            Vector3[] liveWorldLandmarks,
            float[] liveVisibility,
            bool mirror,
            bool coreOnly,
            int minimumRequiredSamples)
        {
            templateWorldSourcePointBuffer.Clear();
            liveWorldSourcePointBuffer.Clear();

            for (int i = 0; i < frame.trackedWorldLandmarks.Length; i++)
            {
                PoseWorldPointSample worldPoint = frame.trackedWorldLandmarks[i];
                if (coreOnly && !IsCoreLandmarkIndex(worldPoint.Index))
                {
                    continue;
                }

                int liveIndex = mirror ? MirrorLandmarkIndex(worldPoint.Index) : worldPoint.Index;
                if (!IsValidLandmarkIndex(liveIndex))
                {
                    continue;
                }

                if (!HasSufficientVisibility(liveVisibility, liveIndex))
                {
                    continue;
                }

                templateWorldSourcePointBuffer.Add(worldPoint.Position);
                liveWorldSourcePointBuffer.Add(liveWorldLandmarks[liveIndex]);
            }

            return templateWorldSourcePointBuffer.Count >= minimumRequiredSamples &&
                liveWorldSourcePointBuffer.Count >= minimumRequiredSamples;
        }

        private static bool IsCoreAngleSample(PoseAngleSample sample)
        {
            return IsCoreLandmarkIndex(sample.A) &&
                IsCoreLandmarkIndex(sample.B) &&
                IsCoreLandmarkIndex(sample.C);
        }

        private static bool IsCoreLandmarkIndex(int index)
        {
            switch (index)
            {
                case 11:
                case 12:
                case 23:
                case 24:
                case 25:
                case 26:
                case 27:
                case 28:
                case 29:
                case 30:
                case 31:
                case 32:
                    return true;
                default:
                    return false;
            }
        }

        private static string ResolveTemplateDisplayName(string rawMotionName)
        {
            return string.IsNullOrWhiteSpace(rawMotionName)
                ? "UnnamedMotion"
                : rawMotionName.Trim();
        }

        private void SetNoMatchStateForAllPlayers(string stateName)
        {
            for (int i = 0; i < playerStates.Length; i++)
            {
                SetNoMatchState(playerStates[i], stateName);
            }
        }

        private void SetNoMatchState(PlayerMotionState playerState, string stateName)
        {
            if (playerState == null)
            {
                return;
            }

            playerState.DetectedMotionName = stateName;
            playerState.DetectedMotionConfidence = 0f;
            PopulateZeroScoresForTemplates(playerState);
            NotifyPlayerMotionScoresUpdated(playerState);
            NotifyPlayerMotionChangedIfNeeded(playerState);
        }

        private void PopulateZeroScoresForTemplates(PlayerMotionState playerState)
        {
            playerState.CurrentScores.Clear();
            playerState.MotionScores.Clear();

            if (templates.Count == 0)
            {
                return;
            }

            HashSet<string> addedMotionNames = new HashSet<string>(StringComparer.Ordinal);
            for (int i = 0; i < templates.Count; i++)
            {
                string motionName = ResolveTemplateDisplayName(templates[i].motionName);
                if (!addedMotionNames.Add(motionName))
                {
                    continue;
                }

                playerState.CurrentScores[motionName] = 0f;
                playerState.MotionScores.Add(new MotionScore
                {
                    motionName = motionName,
                    confidence = 0f
                });
            }
        }

        private void NotifyPlayerMotionChangedIfNeeded(PlayerMotionState playerState)
        {
            bool motionNameChanged = playerState.DetectedMotionName != playerState.LastNotifiedMotionName;
            bool confidenceChanged = Mathf.Abs(playerState.DetectedMotionConfidence - playerState.LastNotifiedMotionConfidence) >= MotionChangeEventConfidenceDelta;
            if (!motionNameChanged && !confidenceChanged)
            {
                return;
            }

            playerState.LastNotifiedMotionName = playerState.DetectedMotionName;
            playerState.LastNotifiedMotionConfidence = playerState.DetectedMotionConfidence;
            OnPlayerMotionChanged?.Invoke(playerState.PlayerSlot, playerState.DetectedMotionName, playerState.DetectedMotionConfidence);

            if (playerState.PlayerSlot == ResolveSelectedPlayerSlot())
            {
                OnMotionChanged?.Invoke(playerState.DetectedMotionName, playerState.DetectedMotionConfidence);
            }
        }

        private void NotifyPlayerMotionScoresUpdated(PlayerMotionState playerState)
        {
            OnPlayerMotionScoresUpdated?.Invoke(playerState.PlayerSlot, playerState.MotionScores);

            if (playerState.PlayerSlot == ResolveSelectedPlayerSlot())
            {
                OnMotionScoresUpdated?.Invoke(playerState.MotionScores);
            }
        }

        private void SyncSelectedPlayerRealtimeOutput()
        {
            PlayerMotionState selectedState = GetPlayerState(ResolveSelectedPlayerSlot());
            detectedMotionName = selectedState.DetectedMotionName;
            detectedMotionConfidence = selectedState.DetectedMotionConfidence;

            currentScores.Clear();
            foreach (KeyValuePair<string, float> pair in selectedState.CurrentScores)
            {
                currentScores[pair.Key] = pair.Value;
            }

            motionScores.Clear();
            motionScores.AddRange(selectedState.MotionScores);
        }

        private void RebuildMotionTemplates()
        {
            templates.Clear();
            maxTemplateDuration = 1f;

            if (motionFiles != null)
            {
                for (int i = 0; i < motionFiles.Count; i++)
                {
                    MotionFileReference motionEntry = motionFiles[i];
                    if (motionEntry == null || motionEntry.motionFile == null)
                    {
                        continue;
                    }

                    if (!TryParseMotionJson(motionEntry.motionFile.text, out MotionFrameTemplate[] frames, out float duration))
                    {
                        Debug.LogWarning("[MotionGestureDetector] Invalid motion JSON (frames with trackedLandmarks, trackedAngles, and/or trackedWorldLandmarks required): " + motionEntry.motionFile.name);
                        continue;
                    }

                    MotionTemplate template = new MotionTemplate
                    {
                        motionName = ResolveMotionName(motionEntry),
                        duration = duration,
                        frames = frames
                    };

                    templates.Add(template);
                    maxTemplateDuration = Mathf.Max(maxTemplateDuration, duration);
                }
            }

            for (int i = 0; i < playerStates.Length; i++)
            {
                PlayerMotionState playerState = playerStates[i];
                playerState.LiveSamples.Clear();
                playerState.NextSampleTime = 0f;
                PopulateZeroScoresForTemplates(playerState);
            }
        }

        private static string ResolveMotionName(MotionFileReference motionEntry)
        {
            if (!string.IsNullOrWhiteSpace(motionEntry.motionName))
            {
                return motionEntry.motionName.Trim();
            }

            if (motionEntry.motionFile != null)
            {
                return motionEntry.motionFile.name;
            }

            return "UnnamedMotion";
        }

        private static bool TryParseMotionJson(string json, out MotionFrameTemplate[] frames, out float duration)
        {
            frames = null;
            duration = 0f;
            if (string.IsNullOrWhiteSpace(json))
            {
                return false;
            }

            MotionJsonData data = JsonUtility.FromJson<MotionJsonData>(json);
            if (data == null || data.frames == null || data.frames.Length == 0)
            {
                return false;
            }

            List<MotionFrameTemplate> parsedFrames = new List<MotionFrameTemplate>(data.frames.Length);
            for (int i = 0; i < data.frames.Length; i++)
            {
                MotionFrameJsonData frameData = data.frames[i];
                if (frameData == null)
                {
                    continue;
                }

                bool hasTrackedLandmarks = TryParseTrackedPosePointData(frameData.trackedLandmarks, out PosePointSample[] trackedLandmarks);
                bool hasTrackedAngles = TryParseTrackedPoseAngleData(frameData.trackedAngles, out PoseAngleSample[] trackedAngles);
                bool hasTrackedWorldLandmarks = TryParseTrackedPoseWorldPointData(frameData.trackedWorldLandmarks, out PoseWorldPointSample[] trackedWorldLandmarks);
                if (!hasTrackedLandmarks && !hasTrackedAngles && !hasTrackedWorldLandmarks)
                {
                    continue;
                }

                parsedFrames.Add(new MotionFrameTemplate
                {
                    time = Mathf.Max(0f, frameData.time),
                    trackedLandmarks = trackedLandmarks,
                    trackedAngles = trackedAngles,
                    trackedWorldLandmarks = trackedWorldLandmarks
                });
            }

            if (parsedFrames.Count < 2)
            {
                return false;
            }

            parsedFrames.Sort((left, right) => left.time.CompareTo(right.time));

            float firstTime = parsedFrames[0].time;
            for (int i = 0; i < parsedFrames.Count; i++)
            {
                parsedFrames[i].time -= firstTime;
            }

            float inferredDuration = parsedFrames[parsedFrames.Count - 1].time;
            duration = data.duration > 0f ? data.duration - firstTime : inferredDuration;
            duration = Mathf.Max(duration, inferredDuration, 0.05f);

            for (int i = 0; i < parsedFrames.Count; i++)
            {
                parsedFrames[i].normalizedTime = duration > 0f ? Mathf.Clamp01(parsedFrames[i].time / duration) : 0f;
            }

            ApplyDeltaBasedMotionFiltering(parsedFrames);

            parsedFrames[0].normalizedTime = 0f;
            parsedFrames[parsedFrames.Count - 1].normalizedTime = 1f;

            frames = parsedFrames.ToArray();
            return true;
        }

        private static void ApplyDeltaBasedMotionFiltering(List<MotionFrameTemplate> frames)
        {
            if (frames == null || frames.Count == 0)
            {
                return;
            }

            float[] landmarkMaxDelta = new float[LandmarkCount];
            float[] landmarkTotalDelta = new float[LandmarkCount];
            bool[] landmarkSeen = new bool[LandmarkCount];
            Vector2[] previousLandmarks = new Vector2[LandmarkCount];
            bool[] hasPreviousLandmarks = new bool[LandmarkCount];

            float[] worldMaxDelta = new float[LandmarkCount];
            float[] worldTotalDelta = new float[LandmarkCount];
            bool[] worldSeen = new bool[LandmarkCount];
            Vector3[] previousWorldLandmarks = new Vector3[LandmarkCount];
            bool[] hasPreviousWorldLandmarks = new bool[LandmarkCount];

            for (int frameIndex = 0; frameIndex < frames.Count; frameIndex++)
            {
                MotionFrameTemplate frame = frames[frameIndex];
                if (frame == null)
                {
                    continue;
                }

                PosePointSample[] trackedLandmarks = frame.trackedLandmarks;
                if (trackedLandmarks != null)
                {
                    for (int i = 0; i < trackedLandmarks.Length; i++)
                    {
                        PosePointSample sample = trackedLandmarks[i];
                        if (!IsValidLandmarkIndex(sample.Index))
                        {
                            continue;
                        }

                        int index = sample.Index;
                        landmarkSeen[index] = true;
                        if (hasPreviousLandmarks[index])
                        {
                            float delta = Vector2.Distance(previousLandmarks[index], sample.Position);
                            landmarkMaxDelta[index] = Mathf.Max(landmarkMaxDelta[index], delta);
                            landmarkTotalDelta[index] += delta;
                        }

                        previousLandmarks[index] = sample.Position;
                        hasPreviousLandmarks[index] = true;
                    }
                }

                PoseWorldPointSample[] trackedWorldLandmarks = frame.trackedWorldLandmarks;
                if (trackedWorldLandmarks != null)
                {
                    for (int i = 0; i < trackedWorldLandmarks.Length; i++)
                    {
                        PoseWorldPointSample sample = trackedWorldLandmarks[i];
                        if (!IsValidLandmarkIndex(sample.Index))
                        {
                            continue;
                        }

                        int index = sample.Index;
                        worldSeen[index] = true;
                        if (hasPreviousWorldLandmarks[index])
                        {
                            float delta = Vector3.Distance(previousWorldLandmarks[index], sample.Position);
                            worldMaxDelta[index] = Mathf.Max(worldMaxDelta[index], delta);
                            worldTotalDelta[index] += delta;
                        }

                        previousWorldLandmarks[index] = sample.Position;
                        hasPreviousWorldLandmarks[index] = true;
                    }
                }
            }

            float[] landmarkMotionScore = new float[LandmarkCount];
            bool[] movingLandmarkMask = new bool[LandmarkCount];
            float landmarkScale = EstimateTemplateLandmarkScale2D(frames);
            float landmarkPeakThreshold = Mathf.Clamp(landmarkScale * MotionDeltaScaleFactor2D, MotionDeltaMin2D, MotionDeltaMax2D);
            float landmarkAccumThreshold = landmarkPeakThreshold * MotionDeltaAccumulationMultiplier;

            for (int index = 0; index < LandmarkCount; index++)
            {
                landmarkMotionScore[index] = landmarkMaxDelta[index] + (landmarkTotalDelta[index] * 0.25f);
                bool isMoving = landmarkSeen[index] &&
                    (landmarkMaxDelta[index] >= landmarkPeakThreshold ||
                     landmarkTotalDelta[index] >= landmarkAccumThreshold);

                if (!isMoving &&
                    landmarkSeen[index] &&
                    IsCoreLandmarkIndex(index) &&
                    landmarkMaxDelta[index] >= landmarkPeakThreshold * MotionDeltaAssistMultiplier)
                {
                    isMoving = true;
                }

                movingLandmarkMask[index] = isMoving;
            }

            EnsureMinimumMovingEntries(movingLandmarkMask, landmarkSeen, landmarkMotionScore, minimumRequired: 2);

            float[] worldMotionScore = new float[LandmarkCount];
            bool[] movingWorldMask = new bool[LandmarkCount];
            float worldScale = EstimateTemplateLandmarkScale3D(frames);
            float worldPeakThreshold = Mathf.Clamp(worldScale * MotionDeltaScaleFactor3D, MotionDeltaMin3D, MotionDeltaMax3D);
            float worldAccumThreshold = worldPeakThreshold * 1.6f;
            int worldSeenCount = 0;

            for (int index = 0; index < LandmarkCount; index++)
            {
                if (worldSeen[index])
                {
                    worldSeenCount++;
                }

                worldMotionScore[index] = worldMaxDelta[index] + (worldTotalDelta[index] * 0.25f);
                bool isMoving = worldSeen[index] &&
                    (worldMaxDelta[index] >= worldPeakThreshold ||
                     worldTotalDelta[index] >= worldAccumThreshold);

                if (!isMoving &&
                    worldSeen[index] &&
                    movingLandmarkMask[index] &&
                    worldMaxDelta[index] >= worldPeakThreshold * MotionDeltaAssistMultiplier)
                {
                    isMoving = true;
                }

                movingWorldMask[index] = isMoving;
            }

            if (worldSeenCount >= 3)
            {
                EnsureMinimumMovingEntries(movingWorldMask, worldSeen, worldMotionScore, minimumRequired: 3);
            }

            Dictionary<ulong, AngleMotionAccumulator> angleAccumulators = new Dictionary<ulong, AngleMotionAccumulator>();
            for (int frameIndex = 0; frameIndex < frames.Count; frameIndex++)
            {
                MotionFrameTemplate frame = frames[frameIndex];
                if (frame == null || frame.trackedAngles == null)
                {
                    continue;
                }

                for (int i = 0; i < frame.trackedAngles.Length; i++)
                {
                    PoseAngleSample sample = frame.trackedAngles[i];
                    ulong key = CreateAngleKey(sample.A, sample.B, sample.C);
                    if (!angleAccumulators.TryGetValue(key, out AngleMotionAccumulator accumulator))
                    {
                        accumulator = new AngleMotionAccumulator(sample.A, sample.B, sample.C);
                        angleAccumulators[key] = accumulator;
                    }

                    if (accumulator.HasLastAngle)
                    {
                        float delta = Mathf.Abs(Mathf.DeltaAngle(accumulator.LastAngle, sample.Angle));
                        accumulator.MaxDelta = Mathf.Max(accumulator.MaxDelta, delta);
                        accumulator.TotalDelta += delta;
                    }

                    accumulator.LastAngle = sample.Angle;
                    accumulator.HasLastAngle = true;
                }
            }

            Dictionary<ulong, float> angleMotionScoreByKey = new Dictionary<ulong, float>(angleAccumulators.Count);
            HashSet<ulong> movingAngleKeys = new HashSet<ulong>();
            foreach (KeyValuePair<ulong, AngleMotionAccumulator> pair in angleAccumulators)
            {
                AngleMotionAccumulator accumulator = pair.Value;
                float score = accumulator.MaxDelta + (accumulator.TotalDelta * 0.2f);
                angleMotionScoreByKey[pair.Key] = score;

                bool isMoving = accumulator.MaxDelta >= AngleMotionDeltaThreshold ||
                    accumulator.TotalDelta >= AngleMotionAccumulationThreshold;

                if (!isMoving &&
                    (movingLandmarkMask[accumulator.A] || movingLandmarkMask[accumulator.B] || movingLandmarkMask[accumulator.C]) &&
                    accumulator.MaxDelta >= AngleMotionDeltaThreshold * MotionDeltaAssistMultiplier)
                {
                    isMoving = true;
                }

                if (isMoving)
                {
                    movingAngleKeys.Add(pair.Key);
                }
            }

            EnsureMinimumMovingAngles(movingAngleKeys, angleMotionScoreByKey, minimumRequired: 1);

            for (int frameIndex = 0; frameIndex < frames.Count; frameIndex++)
            {
                MotionFrameTemplate frame = frames[frameIndex];
                if (frame == null)
                {
                    continue;
                }

                PosePointSample[] filteredLandmarks = FilterLandmarkSamplesByMotion(frame.trackedLandmarks, movingLandmarkMask, landmarkMotionScore, minimumRequired: 2);
                PoseWorldPointSample[] filteredWorldLandmarks = FilterWorldLandmarkSamplesByMotion(frame.trackedWorldLandmarks, movingWorldMask, worldMotionScore, minimumRequired: 3);
                PoseAngleSample[] filteredAngles = FilterAngleSamplesByMotion(frame.trackedAngles, movingAngleKeys, angleMotionScoreByKey, minimumRequired: 1);

                bool hasLandmarkData = filteredLandmarks != null && filteredLandmarks.Length >= 2;
                bool hasAngleData = filteredAngles != null && filteredAngles.Length > 0;
                bool hasWorldData = filteredWorldLandmarks != null && filteredWorldLandmarks.Length >= 3;

                if (!hasLandmarkData && !hasAngleData && !hasWorldData)
                {
                    continue;
                }

                frame.trackedLandmarks = hasLandmarkData ? filteredLandmarks : null;
                frame.trackedAngles = hasAngleData ? filteredAngles : null;
                frame.trackedWorldLandmarks = hasWorldData ? filteredWorldLandmarks : null;
            }
        }

        private static PosePointSample[] FilterLandmarkSamplesByMotion(
            PosePointSample[] samples,
            bool[] movingMask,
            float[] motionScores,
            int minimumRequired)
        {
            if (samples == null || samples.Length == 0)
            {
                return null;
            }

            bool[] include = new bool[samples.Length];
            int includeCount = 0;

            for (int i = 0; i < samples.Length; i++)
            {
                int index = samples[i].Index;
                if (IsValidLandmarkIndex(index) && movingMask != null && index < movingMask.Length && movingMask[index])
                {
                    include[i] = true;
                    includeCount++;
                }
            }

            int targetCount = Mathf.Min(Mathf.Max(minimumRequired, 1), samples.Length);
            while (includeCount < targetCount)
            {
                int bestIndex = -1;
                float bestScore = float.NegativeInfinity;
                for (int i = 0; i < samples.Length; i++)
                {
                    if (include[i])
                    {
                        continue;
                    }

                    int index = samples[i].Index;
                    float score = IsValidLandmarkIndex(index) && motionScores != null && index < motionScores.Length
                        ? motionScores[index]
                        : 0f;

                    if (score > bestScore)
                    {
                        bestScore = score;
                        bestIndex = i;
                    }
                }

                if (bestIndex < 0)
                {
                    break;
                }

                include[bestIndex] = true;
                includeCount++;
            }

            if (includeCount <= 0)
            {
                return null;
            }

            PosePointSample[] filtered = new PosePointSample[includeCount];
            int writeIndex = 0;
            for (int i = 0; i < samples.Length; i++)
            {
                if (!include[i])
                {
                    continue;
                }

                filtered[writeIndex++] = samples[i];
            }

            return filtered;
        }

        private static PoseWorldPointSample[] FilterWorldLandmarkSamplesByMotion(
            PoseWorldPointSample[] samples,
            bool[] movingMask,
            float[] motionScores,
            int minimumRequired)
        {
            if (samples == null || samples.Length == 0)
            {
                return null;
            }

            bool[] include = new bool[samples.Length];
            int includeCount = 0;

            for (int i = 0; i < samples.Length; i++)
            {
                int index = samples[i].Index;
                if (IsValidLandmarkIndex(index) && movingMask != null && index < movingMask.Length && movingMask[index])
                {
                    include[i] = true;
                    includeCount++;
                }
            }

            int targetCount = Mathf.Min(Mathf.Max(minimumRequired, 1), samples.Length);
            while (includeCount < targetCount)
            {
                int bestIndex = -1;
                float bestScore = float.NegativeInfinity;
                for (int i = 0; i < samples.Length; i++)
                {
                    if (include[i])
                    {
                        continue;
                    }

                    int index = samples[i].Index;
                    float score = IsValidLandmarkIndex(index) && motionScores != null && index < motionScores.Length
                        ? motionScores[index]
                        : 0f;

                    if (score > bestScore)
                    {
                        bestScore = score;
                        bestIndex = i;
                    }
                }

                if (bestIndex < 0)
                {
                    break;
                }

                include[bestIndex] = true;
                includeCount++;
            }

            if (includeCount <= 0)
            {
                return null;
            }

            PoseWorldPointSample[] filtered = new PoseWorldPointSample[includeCount];
            int writeIndex = 0;
            for (int i = 0; i < samples.Length; i++)
            {
                if (!include[i])
                {
                    continue;
                }

                filtered[writeIndex++] = samples[i];
            }

            return filtered;
        }

        private static PoseAngleSample[] FilterAngleSamplesByMotion(
            PoseAngleSample[] samples,
            HashSet<ulong> movingAngleKeys,
            Dictionary<ulong, float> angleMotionScores,
            int minimumRequired)
        {
            if (samples == null || samples.Length == 0)
            {
                return null;
            }

            bool[] include = new bool[samples.Length];
            int includeCount = 0;

            for (int i = 0; i < samples.Length; i++)
            {
                ulong key = CreateAngleKey(samples[i].A, samples[i].B, samples[i].C);
                if (movingAngleKeys != null && movingAngleKeys.Contains(key))
                {
                    include[i] = true;
                    includeCount++;
                }
            }

            int targetCount = Mathf.Min(Mathf.Max(minimumRequired, 1), samples.Length);
            while (includeCount < targetCount)
            {
                int bestIndex = -1;
                float bestScore = float.NegativeInfinity;
                for (int i = 0; i < samples.Length; i++)
                {
                    if (include[i])
                    {
                        continue;
                    }

                    ulong key = CreateAngleKey(samples[i].A, samples[i].B, samples[i].C);
                    float score = 0f;
                    if (angleMotionScores != null && angleMotionScores.TryGetValue(key, out float motionScore))
                    {
                        score = motionScore;
                    }

                    if (score > bestScore)
                    {
                        bestScore = score;
                        bestIndex = i;
                    }
                }

                if (bestIndex < 0)
                {
                    break;
                }

                include[bestIndex] = true;
                includeCount++;
            }

            if (includeCount <= 0)
            {
                return null;
            }

            PoseAngleSample[] filtered = new PoseAngleSample[includeCount];
            int writeIndex = 0;
            for (int i = 0; i < samples.Length; i++)
            {
                if (!include[i])
                {
                    continue;
                }

                filtered[writeIndex++] = samples[i];
            }

            return filtered;
        }

        private static float EstimateTemplateLandmarkScale2D(List<MotionFrameTemplate> frames)
        {
            if (frames == null || frames.Count == 0)
            {
                return 0.5f;
            }

            float total = 0f;
            int count = 0;

            for (int frameIndex = 0; frameIndex < frames.Count; frameIndex++)
            {
                MotionFrameTemplate frame = frames[frameIndex];
                if (frame == null || frame.trackedLandmarks == null || frame.trackedLandmarks.Length < 2)
                {
                    continue;
                }

                Vector2 min = new Vector2(float.MaxValue, float.MaxValue);
                Vector2 max = new Vector2(float.MinValue, float.MinValue);
                for (int i = 0; i < frame.trackedLandmarks.Length; i++)
                {
                    Vector2 point = frame.trackedLandmarks[i].Position;
                    min = Vector2.Min(min, point);
                    max = Vector2.Max(max, point);
                }

                float diagonal = Vector2.Distance(min, max);
                if (diagonal <= MinVectorEpsilon)
                {
                    continue;
                }

                total += diagonal;
                count++;
            }

            if (count <= 0)
            {
                return 0.5f;
            }

            return total / count;
        }

        private static float EstimateTemplateLandmarkScale3D(List<MotionFrameTemplate> frames)
        {
            if (frames == null || frames.Count == 0)
            {
                return 1f;
            }

            float total = 0f;
            int count = 0;

            for (int frameIndex = 0; frameIndex < frames.Count; frameIndex++)
            {
                MotionFrameTemplate frame = frames[frameIndex];
                if (frame == null || frame.trackedWorldLandmarks == null || frame.trackedWorldLandmarks.Length < 3)
                {
                    continue;
                }

                Vector3 min = new Vector3(float.MaxValue, float.MaxValue, float.MaxValue);
                Vector3 max = new Vector3(float.MinValue, float.MinValue, float.MinValue);
                for (int i = 0; i < frame.trackedWorldLandmarks.Length; i++)
                {
                    Vector3 point = frame.trackedWorldLandmarks[i].Position;
                    min = Vector3.Min(min, point);
                    max = Vector3.Max(max, point);
                }

                float diagonal = Vector3.Distance(min, max);
                if (diagonal <= MinVectorEpsilon)
                {
                    continue;
                }

                total += diagonal;
                count++;
            }

            if (count <= 0)
            {
                return 1f;
            }

            return total / count;
        }

        private static void EnsureMinimumMovingEntries(bool[] movingMask, bool[] seenMask, float[] motionScore, int minimumRequired)
        {
            if (movingMask == null || seenMask == null || motionScore == null || minimumRequired <= 0)
            {
                return;
            }

            int movingCount = 0;
            int seenCount = 0;
            for (int i = 0; i < movingMask.Length && i < seenMask.Length; i++)
            {
                if (seenMask[i])
                {
                    seenCount++;
                }

                if (movingMask[i])
                {
                    movingCount++;
                }
            }

            int targetCount = Mathf.Min(minimumRequired, seenCount);
            while (movingCount < targetCount)
            {
                int bestIndex = -1;
                float bestScore = float.NegativeInfinity;
                for (int i = 0; i < movingMask.Length && i < seenMask.Length && i < motionScore.Length; i++)
                {
                    if (!seenMask[i] || movingMask[i])
                    {
                        continue;
                    }

                    if (motionScore[i] > bestScore)
                    {
                        bestScore = motionScore[i];
                        bestIndex = i;
                    }
                }

                if (bestIndex < 0)
                {
                    break;
                }

                movingMask[bestIndex] = true;
                movingCount++;
            }
        }

        private static void EnsureMinimumMovingAngles(HashSet<ulong> movingAngleKeys, Dictionary<ulong, float> angleScores, int minimumRequired)
        {
            if (movingAngleKeys == null || angleScores == null || minimumRequired <= 0 || angleScores.Count == 0)
            {
                return;
            }

            int targetCount = Mathf.Min(minimumRequired, angleScores.Count);
            while (movingAngleKeys.Count < targetCount)
            {
                bool found = false;
                ulong bestKey = 0UL;
                float bestScore = float.NegativeInfinity;

                foreach (KeyValuePair<ulong, float> pair in angleScores)
                {
                    if (movingAngleKeys.Contains(pair.Key))
                    {
                        continue;
                    }

                    if (!found || pair.Value > bestScore)
                    {
                        found = true;
                        bestKey = pair.Key;
                        bestScore = pair.Value;
                    }
                }

                if (!found)
                {
                    break;
                }

                movingAngleKeys.Add(bestKey);
            }
        }

        private static ulong CreateAngleKey(int a, int b, int c)
        {
            int left = Mathf.Min(a, c);
            int right = Mathf.Max(a, c);
            return ((ulong)(uint)left << 20) | ((ulong)(uint)b << 10) | (uint)right;
        }

        private static bool TryParseTrackedPosePointData(TrackedPosePoint[] trackedPointData, out PosePointSample[] trackedLandmarks)
        {
            trackedLandmarks = null;
            if (trackedPointData == null || trackedPointData.Length == 0)
            {
                return false;
            }

            List<PosePointSample> points = new List<PosePointSample>(trackedPointData.Length);
            for (int i = 0; i < trackedPointData.Length; i++)
            {
                TrackedPosePoint point = trackedPointData[i];
                if (!IsValidLandmarkIndex(point.index))
                {
                    continue;
                }

                points.Add(new PosePointSample(point.index, new Vector2(point.x, point.y)));
            }

            if (points.Count < 2)
            {
                return false;
            }

            trackedLandmarks = points.ToArray();
            return true;
        }

        private static bool TryParseTrackedPoseAngleData(TrackedPoseAngle[] trackedAngleData, out PoseAngleSample[] trackedAngles)
        {
            trackedAngles = null;
            if (trackedAngleData == null || trackedAngleData.Length == 0)
            {
                return false;
            }

            List<PoseAngleSample> angles = new List<PoseAngleSample>(trackedAngleData.Length);
            for (int i = 0; i < trackedAngleData.Length; i++)
            {
                TrackedPoseAngle angle = trackedAngleData[i];
                if (!IsValidLandmarkIndex(angle.a) ||
                    !IsValidLandmarkIndex(angle.b) ||
                    !IsValidLandmarkIndex(angle.c))
                {
                    continue;
                }

                angles.Add(new PoseAngleSample(angle.a, angle.b, angle.c, Mathf.Clamp(angle.angle, 0f, 180f)));
            }

            if (angles.Count == 0)
            {
                return false;
            }

            trackedAngles = angles.ToArray();
            return true;
        }

        private static bool TryParseTrackedPoseWorldPointData(TrackedPoseWorldPoint[] trackedWorldPointData, out PoseWorldPointSample[] trackedWorldLandmarks)
        {
            trackedWorldLandmarks = null;
            if (trackedWorldPointData == null || trackedWorldPointData.Length == 0)
            {
                return false;
            }

            List<PoseWorldPointSample> points = new List<PoseWorldPointSample>(trackedWorldPointData.Length);
            for (int i = 0; i < trackedWorldPointData.Length; i++)
            {
                TrackedPoseWorldPoint point = trackedWorldPointData[i];
                if (!IsValidLandmarkIndex(point.index))
                {
                    continue;
                }

                points.Add(new PoseWorldPointSample(point.index, new Vector3(point.x, point.y, point.z)));
            }

            if (points.Count < 3)
            {
                return false;
            }

            trackedWorldLandmarks = points.ToArray();
            return true;
        }

        private static bool IsValidLandmarkIndex(int index)
        {
            return index >= 0 && index < LandmarkCount;
        }
    }
}
